import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const resp = await fetch('http://localhost:9999/topics');
  const result = await resp.json();
  return (
    <html lang="en">
      <body className={inter.className}>
      <div>
        <h1><Link href="/">WEB</Link></h1>
        <input type="text" placeholder="search" />
        <ol>
          {result.map((item:{
            id:number, 
            title:string
          })=>{
            return <li key={item.id}><Link href={`/read/${item.id}`}>{item.title}</Link></li>
          })}
        </ol>
        {children}
        <ul>
          <li><Link href="/create">create</Link></li>
        </ul>
      </div>
        
        </body>
    </html>
  );
}
